---
driver:
  name: vagrant

platforms:
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
- name: ubuntu-10.04
  run_list:
  - recipe[apt]
- name: centos-6.5

suites:
- name: default
  run_list: ["recipe[bind]"]
  attributes:
    bind:
      masters: [ "127.0.0.1" ]
      zones:
        attribute: [ "example.com" ]
      options: [ "check-names slave ignore;", "multi-master yes;", "provide-ixfr yes;", "request-ixfr yes;" ]
