---
driver_plugin: vagrant
provisioner: chef_zero

platforms:
- name: centos-6.4
  driver_config:
    attributes:
      dhcp:
        interfaces:
          - eth0:0
- name: ubuntu-12.04
  run_list:
    - recipe[ubuntu]
  driver_config:
    attributes:
      dhcp:
        interfaces:
          - eth0

suites:
- name: default
  run_list:
    - recipe[dhcp_net_setup]
    - recipe[dhcp::server]
  attributes:
    dhcp:
     groups: []
     hosts: all
     networks:
       - 192.168.9.0/24
     options:
       'domain-name': "vm"
       'domain-name-servers': 192.168.9.1

- name: no_bag
  run_list:
    - recipe[dhcp_net_setup]
    - recipe[dhcp::server]
  attributes:
    dhcp:
     use_bags: false
     groups: []
     hosts: all
     networks:
       - 192.168.9.0/24
     options:
       'domain-name': "vm"
       'domain-name-servers': 192.168.9.1


